### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by rpire** [prolajumokeoni/leaderboard#3]
Hello @prolajumokeoni 👋

Your morning session teammates have reviewed your amazing code. We loved the way your page works, however, we have thought of some changes that you might like to implement.

You can take a look at the suggested changes in your [PR](https://github.com/prolajumokeoni/leaderboard/pull/2#pullrequestreview-745784549). If you have further questions about the suggested changes feel free to leave them as a comment below or in your [PR](https://github.com/prolajumokeoni/leaderboard/pull/2#pullrequestreview-745784549). 🤓

Cheers and Happy coding! 🚀

**Comment by prolajumokeoni** [comment]
Thank you guys, I will implement your suggestions!
